const CartActionTypes = {
    ADD_PRODUTO: "ADD_PRODUTO",
    REMOVE_PRODUTO: "REMOVE_PRODUTO",
    INCREMENT_QUANTITY: "INCREMENT_QUANTITY",
    DECREMENT_QUANTITY: "DECREMENT_QUANTITY"
};

export default CartActionTypes;
